CREATE TABLE chat_conversations (
    id UUID PRIMARY KEY,
    direct_key VARCHAR(73) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE chat_members (
    conversation_id UUID NOT NULL REFERENCES chat_conversations(id),
    user_id UUID NOT NULL REFERENCES app_users(id),
    PRIMARY KEY (conversation_id, user_id)
);
CREATE INDEX chat_members_user_idx ON chat_members(user_id, conversation_id);
CREATE TABLE chat_messages (
    sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id UUID NOT NULL UNIQUE,
    conversation_id UUID NOT NULL REFERENCES chat_conversations(id),
    sender_id UUID NOT NULL REFERENCES app_users(id),
    client_id UUID NOT NULL,
    body VARCHAR(4000) NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (conversation_id, sender_id, client_id),
    FOREIGN KEY (conversation_id, sender_id) REFERENCES chat_members(conversation_id, user_id),
    CONSTRAINT message_not_blank CHECK (length(trim(body)) > 0)
);
CREATE INDEX chat_messages_history_idx ON chat_messages(conversation_id, sequence);
